spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.104.70.243:3306/medince
      username: testall
      password: 123456
#   mvc:
#       static-path-pattern: "*.do"
    
mybatis: 
  type-aliases-package: com.medince.pojo
  mapper-locations:
    - com/medince/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
server:
  servlet:
    context-path: /aa
  port: 8080

logging:
  level:
    com.medince.mapper: debug